services:
  controller:
    image: python:latest
    container_name: ansible-controller
    volumes:
      - ./project:/project
    working_dir: /project
    command: pip install ansible && sleep infinity

  target:
    build: ./target
    container_name: target-server
    ports:
      - "2222:22"
      - "5432:5432"
    # 以下は systemctlをコンテナ内で動作させるための設定
    privileged: true
    
    # 以下のディストリビューションではcgroupnsの設定でこちらが使用できる(cgroup v2対応)
    # Fedora (since 31)
    # Debian GNU/Linux (since 11)
    # Ubuntu (since 21.10)
    cgroup: host
    # 以下は systemctlをコンテナ内で動作させるための設定 (cgroup v1対応)
    # volumes:
      # - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    # systemd用のシグナル設定 (コンテナ停止時にsystemdに正しくシグナルを送る)
    stop_signal: SIGRTMIN+3