#SPDX-License-Identifier: MIT-0
---
# tasks file for postgresql

- name: PostgreSQLの設定パスを設定する
  set_fact:
    postgresql_conf_path: "{{ postgresql_conf_path_map[ansible_facts.os_family] }}"

- name: PostgreSQLの再起動コマンドを設定する
  set_fact:
    postgresql_restart_command: "{{ postgresql_restart_command_map[ansible_facts.os_family] }}"
- import_tasks: install_postgresql.yml
- import_tasks: configure_postgresql.yml
