; Akarenga LT のために作成したサンプルダイヤルプラン

;-----------------------------------------
; メインメニュー
;-----------------------------------------
[from-internal]
exten => 2000,1,Answer()
 same => n,Wait(1.5)                               ; RTPストリーム確立待ち（冒頭欠け防止）「nswer() 直後はRTPストリームが確立する前に再生が始まるため、冒頭が欠ける。」
 same => n,NoOp(お電話､ありがとうございます｡エンジニアカフェです)
 same => n,Playback(ja/metan/001_metan_call_thx) ;「お電話ありがとうございます。エンジニアカフェです」
 same => n,Wait(1)                               ; 少し待ってから次のステップへ
 same => n,NoOp(新規ご利用のお申し込みについては､1を｡集中スペースのご利用については､2を｡メーカーズスペースのご予約については､3を｡イベント開催のご相談については､4を押してください｡)
 same => n,Background(ja/metan/002_metan_guidance1) ; ガイダンス（再生中も入力受付）
 same => n,WaitExten(5)

; 1: 新規利用申込 → 受付(内線100)へ転送

exten => 1,1,NoOp(受付に転送いたします｡しばらくお待ち下さい｡)
 same => n,Playback(ja/metan/003_metan_call_bridge)
 same => n,Dial(PJSIP/100,20)
 same => n,Hangup()

; 2: 集中スペース → サブメニューへ
exten => 2,1,Goto(akarenga-focus,s,1)

; 3: MAKER’sスペース → サブメニューへ
exten => 3,1,Goto(akarenga-makers,s,1)

; 4: イベント開催相談 → 受付へ転送
exten => 4,1,NoOp(受付に転送いたします｡しばらくお待ち下さい｡)
 same => n,Playback(ja/metan/003_metan_call_bridge)

 ; CURL のテスト 1~10のユーザーデータをランダムに取得して result 変数にセット
 same => n,Set(result=${CURL(https://jsonplaceholder.typicode.com/users/${RAND(1,10)})})
 same => n,NoOp(CURL RESULT: ${result}) ; CURLの結果をログに出力

 same => n,Dial(PJSIP/100,20)
 same => n,Hangup()

; タイムアウト・無効入力 → メインに戻る
exten => t,1,NoOp(入力を確認できませんでした｡)
 same => n,Playback(ja/metan/008_metan_no_input)
 same => n,Goto(2000,1)

exten => i,1,NoOp(無効な入力です｡)
 same => n,Playback(ja/metan/009_metan_invalid_input)
 same => n,Goto(2000,1)

;-----------------------------------------
; 集中スペース サブメニュー
;-----------------------------------------
[akarenga-focus]
exten => s,1,NoOp(集中スペースのご予約については､1を｡延長については､2を押してください｡)
 same => n,Background(ja/metan/004_metan_guidance2) ;「1:予約、2:延長」（再生中も入力受付）
 same => n,WaitExten(5)

; 1: 予約 → 受付へ転送
exten => 1,1,NoOp(受付に転送いたします｡しばらくお待ち下さい｡)
 same => n,Playback(ja/metan/003_metan_call_bridge)
 same => n,Dial(PJSIP/100,20)
 same => n,Hangup()

; 2: 延長完了
exten => 2,1,NoOp(延長申し込みを完了しました｡)
 same => n,Playback(ja/metan/006_metan_extension_request_confirm)
 same => n,Wait(1)
 same => n,Hangup()

; タイムアウト・無効入力 → このサブメニューに戻る
exten => t,1,NoOp(入力を確認できませんでした｡)
 same => n,Playback(ja/metan/008_metan_no_input)
 same => n,Goto(s,1)

exten => i,1,NoOp(無効な入力です｡)
 same => n,Playback(ja/metan/009_metan_invalid_input)
 same => n,Goto(s,1)

;-----------------------------------------
; MAKER’sスペース サブメニュー
;-----------------------------------------
[akarenga-makers]
exten => s,1,NoOp(機材の初回講習予約については､1を｡レーザー加工機械利用予約については､2を｡スリーディープリンター利用予約については､3を｡CNCフライス盤利用予約については､4を押してください)
 same => n,Background(ja/metan/005_metan_guidance3) ; （再生中も入力受付）
 same => n,WaitExten(5)

; 1〜4: すべて「予約完了」
exten => 1,1,NoOp(利用予約を完了しました｡)
 same => n,Playback(ja/metan/007_metan_request_confirm)
 same => n,Wait(1)
 same => n,Hangup()

exten => 2,1,NoOp(利用予約を完了しました｡)
 same => n,Playback(ja/metan/007_metan_request_confirm)
 same => n,Wait(1)
 same => n,Hangup()

exten => 3,1,NoOp(利用予約を完了しました｡)
 same => n,Playback(ja/metan/007_metan_request_confirm)
 same => n,Wait(1)
 same => n,Hangup()

exten => 4,1,NoOp(利用予約を完了しました｡)
 same => n,Playback(ja/metan/007_metan_request_confirm)
 same => n,Wait(1)
 same => n,Hangup()

; タイムアウト・無効入力 → このサブメニューに戻る
exten => t,1,NoOp(入力を確認できませんでした｡)
 same => n,Playback(ja/metan/008_metan_no_input)
 same => n,Goto(s,1)

exten => i,1,NoOp(無効な入力です｡)
 same => n,Playback(ja/metan/009_metan_invalid_input)
 same => n,Goto(s,1)
