#include "akarenga-guidance.conf"

[globals]
; Dial-Users コンテキストで使用される一般的な内部ダイヤリングオプション。
; ここではタイムアウトのみが定義されています。追加オプションについては、
; Dial アプリのドキュメントを参照してください。
INTERNAL_DIAL_OPT=,30

; 内線xxxにかければpjsip.confのendpoint xxx が鳴る
; 例 => 100にかけると[100]に設定した内線がなる
[from-internal]
exten => _XXX,1,Dial(PJSIP/${EXTEN}${INTERNAL_DIAL_OPT})
same => n,Hangup()

; IVRへの入口（200番にかけるとIVR起動）
exten => 200,1,Goto(from-ivr,s,1)

; https://docs.asterisk.org/Configuration/Dialplan/Pattern-Matching/#order-of-pattern-matching
; アリスが内線6421にダイヤルするとします。彼女のダイヤルプランには以下のパターンがあります。
exten => _6XX1,1,SayAlpha(A)
exten => _64XX,1,SayAlpha(B)
exten => _640X,1,SayAlpha(C)
exten => _6.,1,SayAlpha(D)
exten => _64NX,1,SayAlpha(E)
exten => _6[45]NX,1,SayAlpha(F)
exten => _6[34]NX,1,SayAlpha(G)

; 通話終了時のhangupハンドラ（_[A-Za-z]!より先にhをマッチさせるため明示定義）
exten => h,1,NoOp(Hangup handler)

; アルファベットで始まる番号にマッチさせる例
; この例では任意の一文字以上のアルファベットの単語のフォネティックコードを再生する
exten => _[A-Za-z]!,1,NoOp(アルファベット番号: ${EXTEN})
 same => n,Answer()
 same => n,SayPhonetic(${EXTEN})
 same => n,Hangup()


; IVRの例
[from-ivr]
exten => s,1,Answer()
same => n,Wait(0.5)  ; 少し待ってから次のステップへ
same => n,Playback(ja/hello)  ; "hello" は /var/lib/asterisk/sounds/ja/hello.gsm などの音声ファイルを指す
same => n,Wait(1)  ; 少し待ってから次のステップへ
same => n,WaitExten(10)  ; 10秒間、ユーザーの入力を待つ
exten => _X,1,Playback(ja/digits/${EXTEN})  ; ユーザーが何か入力したら該当する桁の音声を再生
same => n,Wait(1)  ; 少し待ってから切断
same => n,Hangup()

